sudo: required
services:
  - docker

before_install:
  - docker build -t radorna/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true radorna/react-test npm test

after_success:
  - docker build -t radorna/multi-client ./client
  - docker build -t radorna/multi-nginx ./nginx
  - docker build -t radorna/multi-server ./server
  - docker build -t radorna/multi-worker ./worker
  # Log into Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Upload those images into Docker Hub
  - docker push radorna/multi-client
  - docker push radorna/multi-nginx
  - docker push radorna/multi-server
  - docker push radorna/multi-worker